CREATE DATABASE ENCUESTAS_DS;
USE ENCUESTAS_DS;

CREATE TABLE encuesta(
	ID_Encuesta INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(150) NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	Link VARCHAR(250) NOT NULL,
	PRIMARY KEY (ID_PREGUNTA, Nombre)
);

CREATE TABLE pregunta(
	ID_Pregunta INT NOT NULL AUTO_INCREMENT,
	ID_Encuesta INT NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	PRIMARY KEY (ID_PREGUNTA),
	FOREIGN KEY (ID_Encuesta) REFERENCES encuesta(ID_Encuesta)
);

CREATE TABLE respuesta(
	ID_Respuesta INT NOT NULL AUTO_INCREMENT,
	ID_Pregunta INT NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	PRIMARY KEY (ID_Respuesta),
	FOREIGN KEY (ID_Pregunta) REFERENCES pregunta(ID_Pregunta)
);

